/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JComboBox;

/**
 *
 * @author LC01
 */
public class pAdminTruncate extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    Connection connection;
    
    public pAdminTruncate() {
        initComponents();
       
    }
     
    public void addActionListenerAdminTback (ActionListener l) {
        btnback.addActionListener(l);
    }
    
    public void addActionListenerAdminTtruncate (ActionListener l) {
         btntruncate.addActionListener(l);
    }

    public JComboBox<String> getCmbtabel() {
        return cmbtabel;
    }

    public void setCmbtabel(String tabel) {
        cmbtabel.setSelectedItem(tabel);
    }
       
   
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        panelTransparan1 = new com.devproject.component.PanelTransparan();
        btnback = new com.devproject.component.Tombol_Master();
        panelTransparan2 = new com.devproject.component.PanelTransparan();
        btntruncate = new com.devproject.component.Tombol_Master();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbtabel = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.setToolTipText("");
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        panelBackground1.add(panelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 50));

        panelTransparan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntruncate.setForeground(new java.awt.Color(255, 255, 255));
        btntruncate.setText("Truncate");
        btntruncate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan2.add(btntruncate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Table From Database");
        panelTransparan2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATENTION !!!");
        panelTransparan2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("If You Use The Truncate Database, Then All Data From Table Will Delete. You Can't Restore Data Back !!!");
        panelTransparan2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        cmbtabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbtabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "part", "location", "zone", "supplier", "receiving", "issuing" }));
        panelTransparan2.add(cmbtabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 230, 30));

        panelBackground1.add(panelTransparan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1340, 210));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btnback;
    private com.devproject.component.Tombol_Master btntruncate;
    private javax.swing.JComboBox<String> cmbtabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.devproject.component.PanelBackground panelBackground1;
    private com.devproject.component.PanelTransparan panelTransparan1;
    private com.devproject.component.PanelTransparan panelTransparan2;
    // End of variables declaration//GEN-END:variables
}
