/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author LC01
 */
public class pAdminIssuingDetail extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    Connection connection;
    
    public pAdminIssuingDetail() {
        initComponents();
    }

   public void addActionListenerAdminIback (ActionListener l) {
        btncancel.addActionListener(l);
    }

    public void addActionListenerAdminIupdate(ActionListener l) {
         btnupdate.addActionListener(l);
    }
    
    public void addActionListenerAdminIdelete (ActionListener l) {
         btndelete.addActionListener(l);
    }

    public JTextField getTxtpartname() {
        return txtpartname;
    }

    public void setTxtpartname(String partname) {
        txtpartname.setText(partname);
    }

    public JTextField getTxtqty() {
        return txtqty;
    }

    public void setTxtqty(String qty) {
        txtqty.setText(qty);
    }

    public JTextField getTxtissuingno() {
        return txtissuingno;
    }

    public void setTxtissuingno(String issuingno) {
        txtissuingno.setText(issuingno);
    }

    public JDateChooser getTxtdate() {
        return txtdate;
    }

    public void setTxtdate(Date date) {
        txtdate.setDate(date);
    }

    public JTextField getTxtcustomer() {
        return txtcustomer;
    }

    public void setTxtcustomer(String customer) {
        txtcustomer.setText(customer);
    }

    public JTextField getTxtpartnumber() {
        return txtpartnumber;
    }

    public void setTxtpartnumber(String partnumber) {
        txtpartnumber.setText(partnumber);
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        panelTransparan1 = new com.devproject.component.PanelTransparan();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtissuingno = new javax.swing.JTextField();
        txtcustomer = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        btncancel = new com.devproject.component.Tombol_Master();
        btnupdate = new com.devproject.component.Tombol_Master();
        btndelete = new com.devproject.component.Tombol_Master();
        jLabel8 = new javax.swing.JLabel();
        txtpartname = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtpartnumber = new javax.swing.JTextField();
        panelTransparan2 = new com.devproject.component.PanelTransparan();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Issuing No");
        panelTransparan1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaction Date");
        panelTransparan1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer");
        panelTransparan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Part name");
        panelTransparan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty");
        panelTransparan1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtissuingno.setEditable(false);
        txtissuingno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtissuingno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 1190, 30));

        txtcustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerActionPerformed(evt);
            }
        });
        panelTransparan1.add(txtcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 1190, 30));

        txtqty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 1190, 30));

        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, 90, 30));

        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, 90, 30));

        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 340, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Part Number");
        panelTransparan1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtpartname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpartname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpartnameActionPerformed(evt);
            }
        });
        panelTransparan1.add(txtpartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 1190, 30));

        txtdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 1190, 30));

        txtpartnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpartnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpartnumberActionPerformed(evt);
            }
        });
        panelTransparan1.add(txtpartnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 1190, 30));

        panelBackground1.add(panelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1340, 610));

        panelTransparan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Issuing");
        panelTransparan2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 20));

        panelBackground1.add(panelTransparan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerActionPerformed

    private void txtpartnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpartnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpartnameActionPerformed

    private void txtpartnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpartnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpartnumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btncancel;
    private com.devproject.component.Tombol_Master btndelete;
    private com.devproject.component.Tombol_Master btnupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.devproject.component.PanelBackground panelBackground1;
    private com.devproject.component.PanelTransparan panelTransparan1;
    private com.devproject.component.PanelTransparan panelTransparan2;
    private javax.swing.JTextField txtcustomer;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtissuingno;
    private javax.swing.JTextField txtpartname;
    private javax.swing.JTextField txtpartnumber;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

   
}
