/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.MouseAdapter;

/**
 *
 * @author SANDYS
 */
public class pGlass extends javax.swing.JPanel {

    /**
     * Creates new form panelAbout
     */
    private Color colortransparan;
    
    public pGlass() {
        colortransparan = new Color(255, 255, 255, 175);
        initComponents();
        
        addMouseListener(new MouseAdapter() {});
        addMouseMotionListener(new MouseAdapter() {});
        addMouseWheelListener(new MouseAdapter() {});
        addKeyListener(new KeyAdapter() {});
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g = (Graphics2D) grphcs.create();
        g.setColor(colortransparan);
        g.fillRect(0, 0, getWidth(), getHeight());
        g.dispose();
        
        super.paintComponent(grphcs);
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(800, 640));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
