/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LC01
 */
public class pInventory extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    Connection connection;
    
    public pInventory() {
        initComponents();
       
    }
      
    public void addActionListenerinventoryback (ActionListener l) {
        btnback.addActionListener(l);
    }
    
    public void addActionListenerinventoryTabel (MouseListener l) {
         tabelMaster.addMouseListener(l);
    }
     
    public void addActionListenerinventorysearch (ActionListener l) {
         btnsearch.addActionListener(l);
    }
    
    public void addKeyListenerinventorySearch (KeyListener l) {
        txtsearch.addKeyListener(l);
    }
    
    public void addActionListenerinventoryrefresh (ActionListener l) {
         btnrefresh.addActionListener(l);
    }
    
    public void addActionListenerinventorycalculate(ActionListener l) {
         btncalculate.addActionListener(l);
    }
    
    public void addActionListenerinventoryclear(ActionListener l) {
         btnclear.addActionListener(l);
    }
      
    public JTable getTabelMaster() {
        return tabelMaster;
    }

    public JTextField getTxtsearch() {
        return txtsearch;
    }

    public void setTxtsearch(String search) {
        txtsearch.setText(search);
    }

    public JTextField getTxtaverage() {
        return txtaverage;
    }

    public void setTxtaverage(String average) {
        txtaverage.setText(average);
    }

    public JTextField getTxtleadtime() {
        return txtleadtime;
    }

    public void setTxtleadtime(String leadtime) {
        txtleadtime.setText(leadtime);
    }

    public JTextField getTxtmax() {
        return txtmax;
    }

    public void setTxtmax(String max) {
        txtmax.setText(max);
    }

    public JTextField getTxtmin() {
        return txtmin;
    }

    public void setTxtmin(String min) {
        txtmin.setText(min);
    }

    public JTextField getTxtmipmonth() {
        return txtmipmonth;
    }

    public void setTxtmipmonth(String mipmonth) {
        txtmipmonth.setText(mipmonth);
    }

    public JTextField getTxtoc() {
        return txtoc;
    }

    public void setTxtoc(String oc) {
        txtoc.setText(oc);
    }

    public JTextField getTxtoh() {
        return txtoh;
    }

    public void setTxtoh(String oh) {
        txtoh.setText(oh);
    }

    public JTextField getTxtpartname() {
        return txtpartname;
    }

    public void setTxtpartname(String partname) {
        txtpartname.setText(partname);
    }

    public JTextField getTxtpartnumber() {
        return txtpartnumber;
    }

    public void setTxtpartnumber(String partnumber) {
        txtpartnumber.setText(partnumber);
    }

    public JTextField getTxtsoqmonth() {
        return txtsoqmonth;
    }

    public void setTxtsoqmonth(String soqmonth) {
        txtsoqmonth.setText(soqmonth);
    }

    public JTextField getTxtss() {
        return txtss;
    }

    public void setTxtss(String ss) {
        txtss.setText(ss);
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMaster = new javax.swing.JTable();
        panelTransparan1 = new com.devproject.component.PanelTransparan();
        btnrefresh = new com.devproject.component.Tombol_Master();
        txtsearch = new javax.swing.JTextField();
        btnback = new com.devproject.component.Tombol_Master();
        btnsearch = new com.devproject.component.Tombol_Master();
        btncalculate = new com.devproject.component.Tombol_Master();
        btnclear = new com.devproject.component.Tombol_Master();
        panelTransparan2 = new com.devproject.component.PanelTransparan();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtoh = new javax.swing.JTextField();
        txtaverage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpartname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpartnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtss = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtleadtime = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtoc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtmipmonth = new javax.swing.JTextField();
        txtsoqmonth = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMaster.setAutoCreateRowSorter(true);
        tabelMaster.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelMaster.setGridColor(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(tabelMaster);

        panelBackground1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1340, 440));

        panelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 100, 30));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        panelTransparan1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 290, 30));

        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.setToolTipText("");
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.setToolTipText("");
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        panelTransparan1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 100, 30));

        btncalculate.setForeground(new java.awt.Color(255, 255, 255));
        btncalculate.setText("Calculate");
        btncalculate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btncalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 100, 30));

        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 100, 30));

        panelBackground1.add(panelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 50));

        panelTransparan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("On Hand");
        panelTransparan2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Safety Stock");
        panelTransparan2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        txtoh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtoh.setEnabled(false);
        panelTransparan2.add(txtoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 240, 30));

        txtaverage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtaverage.setEnabled(false);
        panelTransparan2.add(txtaverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Part Name");
        panelTransparan2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtpartname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpartname.setEnabled(false);
        panelTransparan2.add(txtpartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 240, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Part Number");
        panelTransparan2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtpartnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpartnumber.setEnabled(false);
        panelTransparan2.add(txtpartnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Minimum Sales");
        panelTransparan2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        txtss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan2.add(txtss, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maximum Sales");
        panelTransparan2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        txtmax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmax.setEnabled(false);
        panelTransparan2.add(txtmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Average (DAD)");
        panelTransparan2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lead Time");
        panelTransparan2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        txtmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmin.setEnabled(false);
        panelTransparan2.add(txtmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 240, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Day");
        panelTransparan2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("/ Day");
        panelTransparan2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        txtleadtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan2.add(txtleadtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 70, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Order Cycle");
        panelTransparan2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        txtoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtoc.setEnabled(false);
        panelTransparan2.add(txtoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 70, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Day");
        panelTransparan2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Suggest Order Quantity (Month)");
        panelTransparan2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Maximum Inventory Position (Month)");
        panelTransparan2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, -1, 30));

        txtmipmonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtmipmonth.setEnabled(false);
        panelTransparan2.add(txtmipmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 330, 30));

        txtsoqmonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsoqmonth.setEnabled(false);
        panelTransparan2.add(txtsoqmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 330, 30));

        panelBackground1.add(panelTransparan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1340, 170));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btnback;
    private com.devproject.component.Tombol_Master btncalculate;
    private com.devproject.component.Tombol_Master btnclear;
    private com.devproject.component.Tombol_Master btnrefresh;
    private com.devproject.component.Tombol_Master btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.devproject.component.PanelBackground panelBackground1;
    private com.devproject.component.PanelTransparan panelTransparan1;
    private com.devproject.component.PanelTransparan panelTransparan2;
    private javax.swing.JTable tabelMaster;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txtleadtime;
    private javax.swing.JTextField txtmax;
    private javax.swing.JTextField txtmin;
    private javax.swing.JTextField txtmipmonth;
    private javax.swing.JTextField txtoc;
    private javax.swing.JTextField txtoh;
    private javax.swing.JTextField txtpartname;
    private javax.swing.JTextField txtpartnumber;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsoqmonth;
    private javax.swing.JTextField txtss;
    // End of variables declaration//GEN-END:variables
}
