/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import java.awt.event.ActionListener;

/**
 *
 * @author LC01
 */
public class pMain extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    public pMain() {
        initComponents();
    }
    
    public void addActionListenerMaster (ActionListener l) {
        btnmaster.addActionListener(l);
    }
    
    public void addActionListenerLocation (ActionListener l) {
        btnlocation.addActionListener(l);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        btnreceiving = new com.devproject.component.Tombol_Master();
        btnmaster = new com.devproject.component.Tombol_Master();
        btnlocation = new com.devproject.component.Tombol_Master();
        btnsupplier = new com.devproject.component.Tombol_Master();
        btnissuing = new com.devproject.component.Tombol_Master();
        btninventory = new com.devproject.component.Tombol_Master();
        btnreport = new com.devproject.component.Tombol_Master();
        btnsetting = new com.devproject.component.Tombol_Master();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnreceiving.setForeground(new java.awt.Color(255, 255, 255));
        btnreceiving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/receive.png"))); // NOI18N
        btnreceiving.setText("Receiving");
        btnreceiving.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreceiving.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreceiving.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnreceiving, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 140, 170));

        btnmaster.setForeground(new java.awt.Color(255, 255, 255));
        btnmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/master.png"))); // NOI18N
        btnmaster.setText("Part Master");
        btnmaster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmaster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmaster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnmaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, 170));

        btnlocation.setForeground(new java.awt.Color(255, 255, 255));
        btnlocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/location3.png"))); // NOI18N
        btnlocation.setText("Location");
        btnlocation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlocation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 140, 170));

        btnsupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/supplier.png"))); // NOI18N
        btnsupplier.setText("Supplier");
        btnsupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 140, 170));

        btnissuing.setForeground(new java.awt.Color(255, 255, 255));
        btnissuing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/issue.png"))); // NOI18N
        btnissuing.setText("Issuing");
        btnissuing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnissuing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnissuing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnissuing, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 140, 170));

        btninventory.setForeground(new java.awt.Color(255, 255, 255));
        btninventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/inventory.png"))); // NOI18N
        btninventory.setText("Inventory");
        btninventory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btninventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btninventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 140, 170));

        btnreport.setForeground(new java.awt.Color(255, 255, 255));
        btnreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/sales.png"))); // NOI18N
        btnreport.setText("Sales Reporting");
        btnreport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnreport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 140, 170));

        btnsetting.setForeground(new java.awt.Color(255, 255, 255));
        btnsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/devproject/img/setting.png"))); // NOI18N
        btnsetting.setText("Setting");
        btnsetting.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsetting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelBackground1.add(btnsetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 140, 170));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btninventory;
    private com.devproject.component.Tombol_Master btnissuing;
    private com.devproject.component.Tombol_Master btnlocation;
    private com.devproject.component.Tombol_Master btnmaster;
    private com.devproject.component.Tombol_Master btnreceiving;
    private com.devproject.component.Tombol_Master btnreport;
    private com.devproject.component.Tombol_Master btnsetting;
    private com.devproject.component.Tombol_Master btnsupplier;
    private com.devproject.component.PanelBackground panelBackground1;
    // End of variables declaration//GEN-END:variables
}
