/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LC01
 */
public class pReceivingnew extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    Connection connection;
    
    public pReceivingnew() {
        initComponents();
    }
    
    public void addActionListenerReceivingnewcancel (ActionListener l) {
        btncancel.addActionListener(l);
    }
    
    public void addKeyListenerreceivingnewSearch (KeyListener l) {
        txtsearch.addKeyListener(l);
    }
    
    public void addActionListenerreceivingnewTabel (MouseListener l) {
         tabelpart.addMouseListener(l);
    }
    
    public void addActionListenerReceivingnewclear(ActionListener l) {
        btnclear.addActionListener(l);
    }
    
    public void addActionListenerReceivingnewsave(ActionListener l) {
        btnsave.addActionListener(l);
    }

    public JComboBox<String> getCmbsupplier() {
        return cmbsupplier;
    }

    public JTable getTabelpart() {
        return tabelpart;
    }

    public JDateChooser getTxtdate() {
        return txtdate;
    }

    public JTextField getTxtpartname() {
        return txtpartname;
    }

    public JTextField getTxtpartnumber() {
        return txtpartnumber;
    }

    public JTextField getTxtqty() {
        return txtqty;
    }

    public JTextField getTxtreceivingno() {
        return txtreceivingno;
    }
    
    public void setCmbsupplier (String Supplier) {
        cmbsupplier.addItem(Supplier);
        cmbsupplier.setSelectedIndex(-1);
    }

    public void setTabelpart(JTable tabelpart) {
        this.tabelpart = tabelpart;
    }

    public void setTxtdate(JDateChooser txtdate) {
        this.txtdate = txtdate;
    }

    public void setTxtpartname(String partname) {
        txtpartname.setText(partname);
    }

    public void setTxtpartnumber(String partnumber) {
        txtpartnumber.setText(partnumber);
    }

    public void setTxtqty(String qty) {
        txtqty.setText(qty);
    }

    public void setTxtreceivingno(String receivingno) {
        txtreceivingno.setText(receivingno);
    }

    public JTextField getTxtsearch() {
        return txtsearch;
    }

    public void setTxtsearch(String search) {
        txtsearch.setText(search);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        panelTransparan1 = new com.devproject.component.PanelTransparan();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        btncancel = new com.devproject.component.Tombol_Master();
        btnsave = new com.devproject.component.Tombol_Master();
        jLabel8 = new javax.swing.JLabel();
        cmbsupplier = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpart = new javax.swing.JTable();
        txtpartname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtreceivingno = new javax.swing.JTextField();
        txtpartnumber = new javax.swing.JTextField();
        btnclear = new com.devproject.component.Tombol_Master();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        panelTransparan2 = new com.devproject.component.PanelTransparan();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Receiving No");
        panelTransparan1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaction Date");
        panelTransparan1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        panelTransparan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qty Receive");
        panelTransparan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 10));

        txtqty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        panelTransparan1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 1180, 30));

        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 550, 90, 30));

        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Part Name");
        panelTransparan1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 10));

        cmbsupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(cmbsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 1180, 30));

        tabelpart.setAutoCreateRowSorter(true);
        tabelpart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelpart);

        panelTransparan1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 1180, 230));

        txtpartname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtpartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 1180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Part Number");
        panelTransparan1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 10));

        txtreceivingno.setEditable(false);
        txtreceivingno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtreceivingno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 580, 30));

        txtpartnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtpartnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 1180, 30));

        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 550, 90, 30));
        panelTransparan1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 460, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Supplier");
        panelTransparan1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 1180, 30));

        panelBackground1.add(panelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1320, 610));

        panelTransparan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Add New Receiving");
        panelTransparan2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 130, 20));

        panelBackground1.add(panelTransparan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btncancel;
    private com.devproject.component.Tombol_Master btnclear;
    private com.devproject.component.Tombol_Master btnsave;
    private javax.swing.JComboBox<String> cmbsupplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.devproject.component.PanelBackground panelBackground1;
    private com.devproject.component.PanelTransparan panelTransparan1;
    private com.devproject.component.PanelTransparan panelTransparan2;
    private javax.swing.JTable tabelpart;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtpartname;
    private javax.swing.JTextField txtpartnumber;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtreceivingno;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

   
}
