/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devproject.form;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LC01
 */
public class pSupplier extends javax.swing.JPanel {

    /**
     * Creates new form pMaster
     */
    Connection connection;
    
    public pSupplier() {
        initComponents();
       
    }

    public void addActionListenerSupplierback (ActionListener l) {
        btnback.addActionListener(l);
    }
    
    public void addActionListenerSuppliersave (ActionListener l) {
        btnsave.addActionListener(l);
    }
    
    public void addActionListenerSupplierupdate (ActionListener l) {
        btnupdate.addActionListener(l);
    }
    
    public void addActionListenerSupplierdelete (ActionListener l) {
        btndelete.addActionListener(l);
    }
    
    public void addActionListenerSupplierrefresh (ActionListener l) {
        btnrefresh.addActionListener(l);
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground1 = new com.devproject.component.PanelBackground();
        btnback = new com.devproject.component.Tombol_Master();
        panelTransparan1 = new com.devproject.component.PanelTransparan();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcontact3 = new javax.swing.JTextField();
        txtsuppliername = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtcontact1 = new javax.swing.JTextField();
        txtcontact2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnrefresh = new com.devproject.component.Tombol_Master();
        btnsave = new com.devproject.component.Tombol_Master();
        btnupdate = new com.devproject.component.Tombol_Master();
        btndelete = new com.devproject.component.Tombol_Master();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelsupplier = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panelBackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBackground1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        panelTransparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact 3");
        panelTransparan1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Supplier Name");
        panelTransparan1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        panelTransparan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtcontact3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtcontact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 1190, 30));

        txtsuppliername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtsuppliername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 1190, 30));

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 1190, 30));

        txtcontact1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtcontact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 1190, 30));

        txtcontact2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(txtcontact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 1190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact 1");
        panelTransparan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact 2");
        panelTransparan1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 80, 30));

        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, 80, 30));

        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 80, 30));

        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelTransparan1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 220, 80, 30));

        panelBackground1.add(panelTransparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1330, 260));

        tabelsupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelsupplier);

        panelBackground1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1330, 360));

        add(panelBackground1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.devproject.component.Tombol_Master btnback;
    private com.devproject.component.Tombol_Master btndelete;
    private com.devproject.component.Tombol_Master btnrefresh;
    private com.devproject.component.Tombol_Master btnsave;
    private com.devproject.component.Tombol_Master btnupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.devproject.component.PanelBackground panelBackground1;
    private com.devproject.component.PanelTransparan panelTransparan1;
    private javax.swing.JTable tabelsupplier;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcontact1;
    private javax.swing.JTextField txtcontact2;
    private javax.swing.JTextField txtcontact3;
    private javax.swing.JTextField txtsuppliername;
    // End of variables declaration//GEN-END:variables
}
